spring:
  application:
    name: wallet-management-ws
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/walletmdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:shafaq0206}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8200
logging:
  level:
    org.springframework.ws: DEBUG
