//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.17 at 11:20:46 AM UZT 
//


package com.example.walletmanagementws.models;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.walletmanagementws.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetInformationRequest_QNAME = new QName("http://models.walletmanagementws.example.com/", "GetInformationRequest");
    private final static QName _GetInformationResponse_QNAME = new QName("http://models.walletmanagementws.example.com/", "GetInformationResponse");
    private final static QName _PerformTransactionRequest_QNAME = new QName("http://models.walletmanagementws.example.com/", "PerformTransactionRequest");
    private final static QName _PerformTransactionResponse_QNAME = new QName("http://models.walletmanagementws.example.com/", "PerformTransactionResponse");
    private final static QName _TransactionStatement_QNAME = new QName("http://models.walletmanagementws.example.com/", "TransactionStatement");
    private final static QName _ChangePasswordRequest_QNAME = new QName("http://models.walletmanagementws.example.com/", "ChangePasswordRequest");
    private final static QName _ChangePasswordResponse_QNAME = new QName("http://models.walletmanagementws.example.com/", "ChangePasswordResponse");
    private final static QName _GetStatementRequest_QNAME = new QName("http://models.walletmanagementws.example.com/", "GetStatementRequest");
    private final static QName _GetStatementResponse_QNAME = new QName("http://models.walletmanagementws.example.com/", "GetStatementResponse");
    private final static QName _CancelTransactionRequest_QNAME = new QName("http://models.walletmanagementws.example.com/", "CancelTransactionRequest");
    private final static QName _CancelTransactionResponse_QNAME = new QName("http://models.walletmanagementws.example.com/", "CancelTransactionResponse");
    private final static QName _CheckTransactionRequest_QNAME = new QName("http://models.walletmanagementws.example.com/", "CheckTransactionRequest");
    private final static QName _CheckTransactionResponse_QNAME = new QName("http://models.walletmanagementws.example.com/", "CheckTransactionResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.walletmanagementws.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetInformationArguments }
     * 
     */
    public GetInformationArguments createGetInformationArguments() {
        return new GetInformationArguments();
    }

    /**
     * Create an instance of {@link GetInformationResult }
     * 
     */
    public GetInformationResult createGetInformationResult() {
        return new GetInformationResult();
    }

    /**
     * Create an instance of {@link PerformTransactionArguments }
     * 
     */
    public PerformTransactionArguments createPerformTransactionArguments() {
        return new PerformTransactionArguments();
    }

    /**
     * Create an instance of {@link PerformTransactionResult }
     * 
     */
    public PerformTransactionResult createPerformTransactionResult() {
        return new PerformTransactionResult();
    }

    /**
     * Create an instance of {@link TransactionDetails }
     * 
     */
    public TransactionDetails createTransactionDetails() {
        return new TransactionDetails();
    }

    /**
     * Create an instance of {@link ChangePasswordArguments }
     * 
     */
    public ChangePasswordArguments createChangePasswordArguments() {
        return new ChangePasswordArguments();
    }

    /**
     * Create an instance of {@link ChangePasswordResult }
     * 
     */
    public ChangePasswordResult createChangePasswordResult() {
        return new ChangePasswordResult();
    }

    /**
     * Create an instance of {@link GetStatementArguments }
     * 
     */
    public GetStatementArguments createGetStatementArguments() {
        return new GetStatementArguments();
    }

    /**
     * Create an instance of {@link GetStatementResult }
     * 
     */
    public GetStatementResult createGetStatementResult() {
        return new GetStatementResult();
    }

    /**
     * Create an instance of {@link CancelTransactionArguments }
     * 
     */
    public CancelTransactionArguments createCancelTransactionArguments() {
        return new CancelTransactionArguments();
    }

    /**
     * Create an instance of {@link CancelTransactionResult }
     * 
     */
    public CancelTransactionResult createCancelTransactionResult() {
        return new CancelTransactionResult();
    }

    /**
     * Create an instance of {@link CheckTransactionArguments }
     * 
     */
    public CheckTransactionArguments createCheckTransactionArguments() {
        return new CheckTransactionArguments();
    }

    /**
     * Create an instance of {@link CheckTransactionResult }
     * 
     */
    public CheckTransactionResult createCheckTransactionResult() {
        return new CheckTransactionResult();
    }

    /**
     * Create an instance of {@link GenericArguments }
     * 
     */
    public GenericArguments createGenericArguments() {
        return new GenericArguments();
    }

    /**
     * Create an instance of {@link GenericParam }
     * 
     */
    public GenericParam createGenericParam() {
        return new GenericParam();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInformationArguments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetInformationArguments }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "GetInformationRequest")
    public JAXBElement<GetInformationArguments> createGetInformationRequest(GetInformationArguments value) {
        return new JAXBElement<GetInformationArguments>(_GetInformationRequest_QNAME, GetInformationArguments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInformationResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetInformationResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "GetInformationResponse")
    public JAXBElement<GetInformationResult> createGetInformationResponse(GetInformationResult value) {
        return new JAXBElement<GetInformationResult>(_GetInformationResponse_QNAME, GetInformationResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PerformTransactionArguments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PerformTransactionArguments }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "PerformTransactionRequest")
    public JAXBElement<PerformTransactionArguments> createPerformTransactionRequest(PerformTransactionArguments value) {
        return new JAXBElement<PerformTransactionArguments>(_PerformTransactionRequest_QNAME, PerformTransactionArguments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PerformTransactionResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PerformTransactionResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "PerformTransactionResponse")
    public JAXBElement<PerformTransactionResult> createPerformTransactionResponse(PerformTransactionResult value) {
        return new JAXBElement<PerformTransactionResult>(_PerformTransactionResponse_QNAME, PerformTransactionResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "TransactionStatement")
    public JAXBElement<TransactionDetails> createTransactionStatement(TransactionDetails value) {
        return new JAXBElement<TransactionDetails>(_TransactionStatement_QNAME, TransactionDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangePasswordArguments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ChangePasswordArguments }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "ChangePasswordRequest")
    public JAXBElement<ChangePasswordArguments> createChangePasswordRequest(ChangePasswordArguments value) {
        return new JAXBElement<ChangePasswordArguments>(_ChangePasswordRequest_QNAME, ChangePasswordArguments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangePasswordResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ChangePasswordResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "ChangePasswordResponse")
    public JAXBElement<ChangePasswordResult> createChangePasswordResponse(ChangePasswordResult value) {
        return new JAXBElement<ChangePasswordResult>(_ChangePasswordResponse_QNAME, ChangePasswordResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatementArguments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStatementArguments }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "GetStatementRequest")
    public JAXBElement<GetStatementArguments> createGetStatementRequest(GetStatementArguments value) {
        return new JAXBElement<GetStatementArguments>(_GetStatementRequest_QNAME, GetStatementArguments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatementResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStatementResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "GetStatementResponse")
    public JAXBElement<GetStatementResult> createGetStatementResponse(GetStatementResult value) {
        return new JAXBElement<GetStatementResult>(_GetStatementResponse_QNAME, GetStatementResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelTransactionArguments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelTransactionArguments }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "CancelTransactionRequest")
    public JAXBElement<CancelTransactionArguments> createCancelTransactionRequest(CancelTransactionArguments value) {
        return new JAXBElement<CancelTransactionArguments>(_CancelTransactionRequest_QNAME, CancelTransactionArguments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelTransactionResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelTransactionResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "CancelTransactionResponse")
    public JAXBElement<CancelTransactionResult> createCancelTransactionResponse(CancelTransactionResult value) {
        return new JAXBElement<CancelTransactionResult>(_CancelTransactionResponse_QNAME, CancelTransactionResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckTransactionArguments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckTransactionArguments }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "CheckTransactionRequest")
    public JAXBElement<CheckTransactionArguments> createCheckTransactionRequest(CheckTransactionArguments value) {
        return new JAXBElement<CheckTransactionArguments>(_CheckTransactionRequest_QNAME, CheckTransactionArguments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckTransactionResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckTransactionResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://models.walletmanagementws.example.com/", name = "CheckTransactionResponse")
    public JAXBElement<CheckTransactionResult> createCheckTransactionResponse(CheckTransactionResult value) {
        return new JAXBElement<CheckTransactionResult>(_CheckTransactionResponse_QNAME, CheckTransactionResult.class, null, value);
    }

}
