//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.17 at 11:20:46 AM UZT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://models.walletmanagementws.example.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.walletmanagementws.models;
